In [1]:
#List comprehensions continued

[x**2 for x in range(8)]

[0, 1, 4, 9, 16, 25, 36, 49]

In [2]:
#Same operattion using map and lambda

list(map(lambda x : x**2,range(8)))

[0, 1, 4, 9, 16, 25, 36, 49]

In [3]:
#Three ways to do even number filtering 

[x for x in range(8) if x%2 == 0]

[0, 2, 4, 6]

In [4]:
list(filter(lambda x: x%2==0,range(8)))   #filter checks the condition

[0, 2, 4, 6]

In [5]:
#creating a function and using it

res = []
for x in range(8):
    if x%2 == 0:
        res.append(x)

res

[0, 2, 4, 6]

In [6]:
#square operation but using map

list(map((lambda x: x**2), filter((lambda x: x % 2 ==0), range(8))))

[0, 4, 16, 36]

In [7]:
#for clauses within a nested list work like equivalent nested for loop

res = [x+y for x in [1,2] for y in [100,200,300]]
res

[101, 201, 301, 102, 202, 302]

In [8]:
#same effect but using a more verbose equivalent

res = []
for x in [1,2,3]:
    for y in [100,200,300]:
        res.append(x+y)
res

[101, 201, 301, 102, 202, 302, 103, 203, 303]

In [9]:
#list constructors can also iterate over other sequence types

[x+y for x in 'spam' for y in 'SPAM']

['sS',
 'sP',
 'sA',
 'sM',
 'pS',
 'pP',
 'pA',
 'pM',
 'aS',
 'aP',
 'aA',
 'aM',
 'mS',
 'mP',
 'mA',
 'mM']

In [10]:
#other complex list operations

[(x,y) for x in range(5) if x%2 == 0 for y in range(5) if y%2==1]

[(0, 1), (0, 3), (2, 1), (2, 3), (4, 1), (4, 3)]

In [11]:
res = []
for x in range(5):
    if x%2==0:
        for y in range(5):
            if y%2==1:
                res.append((x,y))
            
res

[(0, 1), (0, 3), (2, 1), (2, 3), (4, 1), (4, 3)]

In [12]:
#map & filter equivalent
[(x,y) for x in list(map(lambda x: x,filter(lambda x:x%2==0,range(5)))) for y in list(map(lambda x: x,filter(lambda x:x%2==1,range(5))))]


[(0, 1), (0, 3), (2, 1), (2, 3), (4, 1), (4, 3)]

#### List Comprehension s and Matrices

In [13]:
#declaring matrix
#used pytorch to generate matrix easily
import torch
M = [[1,2,3],[4,5,6],[7,8,9]]
M1 = torch.tensor(M)
N1 = M1+11
torch.matmul(M1,N1) #example matrix multiplication using torch

N = N1.tolist()

In [14]:
N1

tensor([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20]])

In [15]:
#matmul using torch

torch.matmul(M1,N1)

tensor([[ 96, 102, 108],
        [231, 246, 261],
        [366, 390, 414]])

In [16]:
#Matrix multiplication using generic python

#This just creates a hadamard product ans not matrix multiplication
[[M[row][col] * N[row][col] for row in range(3)] for col in range(3)]

[[12, 60, 126], [26, 80, 152], [42, 102, 180]]

#### Comprehending List Comprehensions

In [17]:
F = open('myfile.txt','w')
F.write('bbb\n')

4

In [18]:
F.write('bbb\n')
F.write('ccc\n')

4

In [19]:
open('myfile.txt','r').readlines()


[]

In [20]:
[line.rstrip() for line in open('myfile.txt').readlines()]

[]

In [21]:
[line.rstrip() for line in open('myfile.txt')]

[]

In [22]:
list(map((lambda line: line.rstrip()), open('myfile.txt')))

[]

In [23]:
listoftuple = [('bob', 35, 'mgr'), ('mel', 40, 'dev')]
listoftuple[0]

('bob', 35, 'mgr')

In [24]:
[age[1] for age in listoftuple]

[35, 40]

In [25]:
list(map((lambda x: x[1]), listoftuple))

[35, 40]

In [26]:
##another way of doing it
#this can only be done on python 2.6 not in 3.0
#list(map((lambda (name, age,job): age), listoftuple))

### Iterators revisited

In [27]:
def gensquares(N):
    for i in range(N):
        yield i**2

In [28]:
x = gensquares(2)
next(x)
next(x)

1

In [29]:
for i in gensquares(5):
    print(i, end=':')

0:1:4:9:16:

In [30]:
x = gensquares(5)
x    #generator function call


<generator object gensquares at 0x7f51fa104d60>

In [31]:
#using for loop
for x in [i**2 for i in range(5)]:
    print(x, end = ' ')

0 1 4 9 16 

In [32]:
for x in map((lambda x: x**2), [i for i in range(5)]):
    print(x, end = ' : ')

0 : 1 : 4 : 9 : 16 : 

##### Extended generator function protocol: send versus next

In [33]:
def gen():
    for i in range(10):
        X = yield i
        print(X)

gen().__next__() 

0

In [34]:
G = gen()

In [35]:
next(G)

0

In [36]:
G.send(88)

88


1

#### Generator Expressions: Iterators Meet Comprehensions

In [37]:
#Generator expresssions are like list comprehensions but enclosed in parentheses instead
[x**2 for x in range(6)]    #list comprehension #compiles in memory
(x**2 for x in range(6))    #generator expresssion #compiles on call

#for example

G = (x**2 for x in range(10))
G.__next__()
G.__next__()    #iterates over and generates
next(G)         #also does the same thing

4

In [38]:
#other way
G = (x**2 for x in range(10))        #also iterable

def nextg(G):
    for i in G:
        print(i)

In [39]:
print(nextg(G))

0
1
4
9
16
25
36
49
64
81
None


In [40]:
for num in (x**2 for x in range(10)):
    print ('%s,%s'%(num, num/2.0))

0,0.0
1,0.5
4,2.0
9,4.5
16,8.0
25,12.5
36,18.0
49,24.5
64,32.0
81,40.5


In [41]:
import torch
A = torch.zeros((113,221))
A

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [42]:
any(A.tolist()[0])

False

In [43]:
import math
list(map(math.sqrt,(i**2 for i in range(5))))

[0.0, 1.0, 2.0, 3.0, 4.0]

#### Generator Functions Versus Generator Expressions

In [7]:
G = (x*4 for x in 'SPAM')
I = iter(G)
next(I)
next(I)
G is iter(G)    #Generator expressions are iterator on itself

True

In [10]:
#manual function


def timesfour(G):
    for x in G:
        yield x*4

G = timesfour('spam')
list(G)

['ssss', 'pppp', 'aaaa', 'mmmm']

In [12]:
#unlike generator expressions lists support multiple iterations

L = [1,2,3,4]
I1, I2 = iter(L),iter(L)

next(I1),next(I1), next(I2)  #iteration of I2 is different from I1

(1, 2, 1)

In [14]:
#zip is also an iterable

S1 = 'abc'
S2 = 'xyz123'

list(zip(S1,S2))  #iterates and zips

[('a', 'x'), ('b', 'y'), ('c', 'z')]

In [16]:

list(zip([-2,-1,0,1,2],[-2,-1,0,1,2],[-2,-1,0,1,2]))

[(-2, -2, -2), (-1, -1, -1), (0, 0, 0), (1, 1, 1), (2, 2, 2)]

In [19]:
#while map

list(map(pow, [-2,-1,0,1,2],[1,2,3,4,5]))

[-2, 1, 0, 1, 32]

In [26]:
#creating mymap function

def mymap(func, *args):
    res=[]
    for x in zip(*args):
        res.append(func(*x))
    return res


print(mymap(abs, [-1,-5,-5]))
print(mymap(pow, [1,2,3],[3,2,1]))

[1, 5, 5]
[1, 4, 3]


In [29]:
#above function using list  comprehensio

def mymap(func, *args):
    return [func(*args) for args in zip(*args) ]

mymap(abs, [-2,-4,-5])

[2, 4, 5]

In [32]:
#using generator expression
def mymap(func, *args):
    res = []
    for arg in zip(*args):
        yield func(*arg)

mymap(abs, [-3,-2,-1]).__next__()

3

In [36]:
list(mymap(abs, [-3,-2,-1]))

[3, 2, 1]

In [9]:
#myzip function

def myzip(*seqs):
    seq = [list(S) for S in seqs]
    while all(seqs):
        yield tuple(S.pop(0) for S in seqs)

(myzip([1,2,3,4,5])).__next__()

(1,)

In [15]:
def mymappad(*seqs, pad=None):
    seqs = [list(S) for S in seqs]
    while any(seqs):
        yield tuple((S.pop(0) if S else pad) for S in seqs)

mymappad([1,2,3,4,5]).__next__()

(1,)

In [17]:
#Dictionary comprehension

{x: x*x for x in range(10)}    #generates a dictionary

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}

In [19]:
#statement based equivalents
res = set()
for x in range(10):
    res.add(x*x)
res

{0, 1, 4, 9, 16, 25, 36, 49, 64, 81}

In [22]:
res = {}
for x in range(10):
    res[x] = x*x

res

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}

In [24]:
#generator expression to create key and value on demand
G =((x,x*x) for x in range(10))
G.__next__()

(0, 0)

In [30]:
#sets and dictionaries also support extended comprehension like lists

[x*x for x in range(10) if x%3==0]
{x*x for x in range(10) if x%3==0}
{x:x*x for x in range(10) if x%3==0}



#nested for loops also work

[(x*3+y*4) for x in range(10) for y in range(10)]
{x: y for x in 'spam' for y in 'ham'}

{'s': 'm', 'p': 'm', 'a': 'm', 'm': 'm'}

In [34]:
{x:y for x in [1,2,3] for y in [4,5,6]}
{x+y for x in 'spam' for y in 'ham'}
{k*2 for k in ['spam','ham','sausage'] if k[0] == 's'}
{k.upper():k for k in ['spam','ham','sausage'] if k[0] == 's'}

{'SPAM': 'spam', 'SAUSAGE': 'sausage'}