In [1]:
#List comprehensions continued

[x**2 for x in range(8)]

[0, 1, 4, 9, 16, 25, 36, 49]

In [2]:
#Same operattion using map and lambda

list(map(lambda x : x**2,range(8)))

[0, 1, 4, 9, 16, 25, 36, 49]

In [3]:
#Three ways to do even number filtering 

[x for x in range(8) if x%2 == 0]

[0, 2, 4, 6]

In [4]:
list(filter(lambda x: x%2==0,range(8)))   #filter checks the condition

[0, 2, 4, 6]

In [5]:
#creating a function and using it

res = []
for x in range(8):
    if x%2 == 0:
        res.append(x)

res

[0, 2, 4, 6]

In [6]:
#square operation but using map

list(map((lambda x: x**2), filter((lambda x: x % 2 ==0), range(8))))

[0, 4, 16, 36]

In [7]:
#for clauses within a nested list work like equivalent nested for loop

res = [x+y for x in [1,2] for y in [100,200,300]]
res

[101, 201, 301, 102, 202, 302]

In [8]:
#same effect but using a more verbose equivalent

res = []
for x in [1,2,3]:
    for y in [100,200,300]:
        res.append(x+y)
res

[101, 201, 301, 102, 202, 302, 103, 203, 303]

In [9]:
#list constructors can also iterate over other sequence types

[x+y for x in 'spam' for y in 'SPAM']

['sS',
 'sP',
 'sA',
 'sM',
 'pS',
 'pP',
 'pA',
 'pM',
 'aS',
 'aP',
 'aA',
 'aM',
 'mS',
 'mP',
 'mA',
 'mM']

In [10]:
#other complex list operations

[(x,y) for x in range(5) if x%2 == 0 for y in range(5) if y%2==1]

[(0, 1), (0, 3), (2, 1), (2, 3), (4, 1), (4, 3)]

In [11]:
res = []
for x in range(5):
    if x%2==0:
        for y in range(5):
            if y%2==1:
                res.append((x,y))
            
res

[(0, 1), (0, 3), (2, 1), (2, 3), (4, 1), (4, 3)]

In [12]:
#map & filter equivalent
[(x,y) for x in list(map(lambda x: x,filter(lambda x:x%2==0,range(5)))) for y in list(map(lambda x: x,filter(lambda x:x%2==1,range(5))))]


[(0, 1), (0, 3), (2, 1), (2, 3), (4, 1), (4, 3)]

#### List Comprehension s and Matrices

In [14]:
#declaring matrix
#used pytorch to generate matrix easily
import torch
M = [[1,2,3],[4,5,6],[7,8,9]]
M1 = torch.tensor(M)
N1 = M1+11
torch.matmul(M1,N1) #example matrix multiplication using torch

N = N1.tolist()

In [16]:
N1

tensor([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20]])

In [17]:
#matmul using torch

torch.matmul(M1,N1)

tensor([[ 96, 102, 108],
        [231, 246, 261],
        [366, 390, 414]])

In [18]:
#Matrix multiplication using generic python

#This just creates a hadamard product ans not matrix multiplication
[[M[row][col] * N[row][col] for row in range(3)] for col in range(3)]

[[12, 60, 126], [26, 80, 152], [42, 102, 180]]

#### Comprehending List Comprehensions

In [19]:
F = open('myfile.txt','w')
F.write('bbb\n')

4

In [20]:
F.write('bbb\n')
F.write('ccc\n')

4

In [21]:
open('myfile.txt','r').readlines()


[]

In [22]:
[line.rstrip() for line in open('myfile.txt').readlines()]

[]

In [23]:
[line.rstrip() for line in open('myfile.txt')]

[]

In [24]:
list(map((lambda line: line.rstrip()), open('myfile.txt')))

[]

In [25]:
listoftuple = [('bob', 35, 'mgr'), ('mel', 40, 'dev')]
listoftuple[0]

('bob', 35, 'mgr')

In [26]:
[age[1] for age in listoftuple]

[35, 40]

In [27]:
list(map((lambda x: x[1]), listoftuple))

[35, 40]

In [28]:
##another way of doing it
#this can only be done on python 2.6 not in 3.0
#list(map((lambda (name, age,job): age), listoftuple))

### Iterators revisited

In [29]:
def gensquares(N):
    for i in range(N):
        yield i**2

In [30]:
x = gensquares(2)
next(x)
next(x)

1

In [31]:
for i in gensquares(5):
    print(i, end=':')

0:1:4:9:16:

In [32]:
x = gensquares(5)
x    #generator function call


<generator object gensquares at 0x7fa4835cf220>

In [33]:
#using for loop
for x in [i**2 for i in range(5)]:
    print(x, end = ' ')

0 1 4 9 16 

In [34]:
for x in map((lambda x: x**2), [i for i in range(5)]):
    print(x, end = ' : ')

0 : 1 : 4 : 9 : 16 : 

##### Extended generator function protocol: send versus next

In [35]:
def gen():
    for i in range(10):
        X = yield i
        print(X)

gen().__next__() 

0

In [36]:
G = gen()

In [37]:
next(G)

0

In [38]:
G.send(88)

88


1

#### Generator Expressions: Iterators Meet Comprehensions

In [39]:
#Generator expresssions are like list comprehensions but enclosed in parentheses instead
[x**2 for x in range(6)]    #list comprehension #compiles in memory
(x**2 for x in range(6))    #generator expresssion #compiles on call

#for example

G = (x**2 for x in range(10))
G.__next__()
G.__next__()    #iterates over and generates
next(G)         #also does the same thing

4

In [40]:
#other way
G = (x**2 for x in range(10))        #also iterable

def nextg(G):
    for i in G:
        print(i)

In [41]:
print(nextg(G))

0
1
4
9
16
25
36
49
64
81
None


In [42]:
for num in (x**2 for x in range(10)):
    print ('%s,%s'%(num, num/2.0))

0,0.0
1,0.5
4,2.0
9,4.5
16,8.0
25,12.5
36,18.0
49,24.5
64,32.0
81,40.5


In [43]:
import torch
A = torch.zeros((113,221))
A

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [44]:
any(A.tolist()[0])

False

In [45]:
import math
list(map(math.sqrt,(i**2 for i in range(5))))

[0.0, 1.0, 2.0, 3.0, 4.0]

In [46]:
math.sqrt((i**2 for i in range(5)))

TypeError: must be real number, not generator